version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - bot
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - bot
  - package-ecosystem: "gitsubmodule"
    directory: "package/astronvim_config"
    schedule:
      interval: "daily"
    labels:
      - dependencies
      - bot
