name: ci

on: 
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run dagger
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project update
            do test
