name: test
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: Run Dagger pipeline
        run: |
          cd ci/pipeline
          go run main.go
